### ISSUE TITLE
Postman collection

### ISSUE THREAD

**Issue by tfedorov** [CoffeeJUG/traffic-rules-for-children#7]
Collection REST API for communication bakcend &  frontenx

**Comment by sergiykatriuk** [comment]
Created:
Postman team workspace "traffic-rules-for-children".
Collection "game-endpoints".

In this collection added all two enpoints.
https://warped-shadow-8604.postman.co/collections/2116658-86b1cb83-2240-42f2-b550-ae3d5b89e1a9?version=latest&workspace=d8567674-a181-4b64-a717-1ae901e8aaea#5ea50c50-bc47-46ca-9f40-0e0e9ca4fb98

**Comment by SeriyBg** [comment]
Done
